# Generated by Django 4.1.3 on 2022-11-07 19:22

import django.utils.timezone
from django.db import migrations, models

import stator.models
import users.models.follow


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="state",
            field=stator.models.StateField(
                choices=[
                    ("pending", "pending"),
                    ("requested", "requested"),
                    ("accepted", "accepted"),
                ],
                default="pending",
                graph=users.models.follow.FollowStates,
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="follow",
            name="state_attempted",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="follow",
            name="state_changed",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
