# Generated by Django 4.1.3 on 2022-11-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_identity_discoverable"),
    ]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="followers_uri",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="identity",
            name="following_uri",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="identity",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="identity",
            name="pinned",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="identity",
            name="shared_inbox_uri",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
