# Generated by Django 4.1.3 on 2022-11-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_follow_state_follow_state_attempted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="accepted",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="requested",
        ),
        migrations.AddField(
            model_name="follow",
            name="state_locked",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="follow",
            name="state_runner",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
