# Generated by Django 4.1.4 on 2022-12-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_identity_followers_etc"),
    ]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="admin_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="identity",
            name="restriction",
            field=models.IntegerField(
                choices=[(0, "None"), (1, "Limited"), (2, "Blocked")], default=0
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="sensitive",
            field=models.BooleanField(default=False),
        ),
    ]
