# Generated by Django 4.1.3 on 2022-11-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_follow_accepted_remove_follow_requested_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="state_locked",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="state_runner",
        ),
    ]
