# Generated by Django 4.1.3 on 2022-11-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_follow_state_locked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="state_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="follow",
            name="state_ready",
            field=models.BooleanField(default=False),
        ),
    ]
