# Generated by Django 4.1.4 on 2022-12-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="actor_type",
            field=models.CharField(default="person", max_length=100),
        ),
    ]
