# Generated by Django 4.1.4 on 2022-12-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_identity_actor_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invite",
            name="email",
        ),
        migrations.AddField(
            model_name="invite",
            name="expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invite",
            name="uses",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
