# Generated by Django 4.1.4 on 2023-01-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_follow_boosts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="restriction",
            field=models.IntegerField(
                choices=[(0, "None"), (1, "Limited"), (2, "Blocked")],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AddIndex(
            model_name="inboxmessage",
            index=models.Index(
                fields=["state", "state_attempted"],
                name="ix_inboxmessag_state_attempted",
            ),
        ),
        migrations.AddIndex(
            model_name="inboxmessage",
            index=models.Index(
                condition=models.Q(("state_locked_until__isnull", False)),
                fields=["state_locked_until", "state"],
                name="ix_inboxmessag_state_locked",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordreset",
            index=models.Index(
                fields=["state", "state_attempted"],
                name="ix_passwordres_state_attempted",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordreset",
            index=models.Index(
                condition=models.Q(("state_locked_until__isnull", False)),
                fields=["state_locked_until", "state"],
                name="ix_passwordres_state_locked",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["state", "state_attempted"], name="ix_report_state_attempted"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                condition=models.Q(("state_locked_until__isnull", False)),
                fields=["state_locked_until", "state"],
                name="ix_report_state_locked",
            ),
        ),
    ]
