# Generated by Django 4.1.4 on 2023-01-13 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_domain_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The text of your announcement.\nAccepts Markdown for formatting."
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="If this announcement will appear on the site.\nIt must still be between start and end times, if provided.",
                    ),
                ),
                (
                    "start",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the announcement will start appearing.\nLeave blank to have it begin as soon as it is published.",
                        null=True,
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the announcement will stop appearing.\nLeave blank to have it display indefinitely.",
                        null=True,
                    ),
                ),
                ("include_unauthenticated", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "seen",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
