# Generated by Django 4.1.5 on 2023-01-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="end",
            field=models.DateTimeField(
                blank=True,
                help_text="When the announcement will stop appearing.\nLeave blank to have it display indefinitely.\nFormat: <code>2023-01-01</code> or <code>2023-01-01 12:30:00</code>",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="start",
            field=models.DateTimeField(
                blank=True,
                help_text="When the announcement will start appearing.\nLeave blank to have it begin as soon as it is published.\nFormat: <code>2023-01-01</code> or <code>2023-01-01 12:30:00</code>",
                null=True,
            ),
        ),
    ]
