# Generated by Django 4.1.4 on 2023-02-04 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_block_states"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="block",
            index_together={("state_ready", "state_locked_until", "state")},
        ),
        migrations.AlterIndexTogether(
            name="domain",
            index_together={("state_ready", "state_locked_until", "state")},
        ),
        migrations.AlterIndexTogether(
            name="follow",
            index_together={("state_ready", "state_locked_until", "state")},
        ),
        migrations.AlterIndexTogether(
            name="identity",
            index_together={("state_ready", "state_locked_until", "state")},
        ),
        migrations.AlterIndexTogether(
            name="inboxmessage",
            index_together={("state_ready", "state_locked_until", "state")},
        ),
        migrations.AlterIndexTogether(
            name="passwordreset",
            index_together={("state_ready", "state_locked_until", "state")},
        ),
        migrations.AlterIndexTogether(
            name="report",
            index_together={("state_ready", "state_locked_until", "state")},
        ),
    ]
