# Generated by Django 4.1.7 on 2023-04-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_hashtagfollow"),
    ]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="featured_collection_uri",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
