# Generated by Django 4.2.1 on 2023-05-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_identity_featured_collection_uri"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="block",
            new_name="users_block_state_r_e016a2_idx",
            old_fields=("state_ready", "state_locked_until", "state"),
        ),
        migrations.RenameIndex(
            model_name="domain",
            new_name="users_domai_state_r_42b328_idx",
            old_fields=("state_ready", "state_locked_until", "state"),
        ),
        migrations.RenameIndex(
            model_name="follow",
            new_name="users_follo_state_r_d1dbc2_idx",
            old_fields=("state_ready", "state_locked_until", "state"),
        ),
        migrations.RenameIndex(
            model_name="identity",
            new_name="users_ident_state_r_6fdeee_idx",
            old_fields=("state_ready", "state_locked_until", "state"),
        ),
        migrations.RenameIndex(
            model_name="inboxmessage",
            new_name="users_inbox_state_r_00fce2_idx",
            old_fields=("state_ready", "state_locked_until", "state"),
        ),
        migrations.RenameIndex(
            model_name="passwordreset",
            new_name="users_passw_state_r_f54f10_idx",
            old_fields=("state_ready", "state_locked_until", "state"),
        ),
        migrations.RenameIndex(
            model_name="report",
            new_name="users_repor_state_r_345b80_idx",
            old_fields=("state_ready", "state_locked_until", "state"),
        ),
        migrations.AddIndex(
            model_name="block",
            index=models.Index(
                fields=["state", "state_attempted"], name="ix_block_state_attempted"
            ),
        ),
        migrations.AddIndex(
            model_name="block",
            index=models.Index(
                condition=models.Q(("state_locked_until__isnull", False)),
                fields=["state_locked_until", "state"],
                name="ix_block_state_locked",
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["state", "state_attempted"], name="ix_follow_state_attempted"
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                condition=models.Q(("state_locked_until__isnull", False)),
                fields=["state_locked_until", "state"],
                name="ix_follow_state_locked",
            ),
        ),
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(
                fields=["state", "state_attempted"], name="ix_identity_state_attempted"
            ),
        ),
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(
                condition=models.Q(("state_locked_until__isnull", False)),
                fields=["state_locked_until", "state"],
                name="ix_identity_state_locked",
            ),
        ),
    ]
