# Generated by Django 4.2.1 on 2023-07-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_index_together_migration"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="block",
            name="users_block_state_r_e016a2_idx",
        ),
        migrations.RemoveIndex(
            model_name="block",
            name="ix_block_state_attempted",
        ),
        migrations.RemoveIndex(
            model_name="block",
            name="ix_block_state_locked",
        ),
        migrations.RemoveIndex(
            model_name="domain",
            name="ix_domain_state_attempted",
        ),
        migrations.RemoveIndex(
            model_name="domain",
            name="ix_domain_state_locked",
        ),
        migrations.RemoveIndex(
            model_name="domain",
            name="users_domai_state_r_42b328_idx",
        ),
        migrations.RemoveIndex(
            model_name="follow",
            name="users_follo_state_r_d1dbc2_idx",
        ),
        migrations.RemoveIndex(
            model_name="follow",
            name="ix_follow_state_attempted",
        ),
        migrations.RemoveIndex(
            model_name="follow",
            name="ix_follow_state_locked",
        ),
        migrations.RemoveIndex(
            model_name="identity",
            name="users_ident_state_r_6fdeee_idx",
        ),
        migrations.RemoveIndex(
            model_name="identity",
            name="ix_identity_state_attempted",
        ),
        migrations.RemoveIndex(
            model_name="identity",
            name="ix_identity_state_locked",
        ),
        migrations.RemoveIndex(
            model_name="inboxmessage",
            name="ix_inboxmessag_state_attempted",
        ),
        migrations.RemoveIndex(
            model_name="inboxmessage",
            name="ix_inboxmessag_state_locked",
        ),
        migrations.RemoveIndex(
            model_name="inboxmessage",
            name="users_inbox_state_r_00fce2_idx",
        ),
        migrations.RemoveIndex(
            model_name="passwordreset",
            name="ix_passwordres_state_attempted",
        ),
        migrations.RemoveIndex(
            model_name="passwordreset",
            name="ix_passwordres_state_locked",
        ),
        migrations.RemoveIndex(
            model_name="passwordreset",
            name="users_passw_state_r_f54f10_idx",
        ),
        migrations.RemoveIndex(
            model_name="report",
            name="ix_report_state_attempted",
        ),
        migrations.RemoveIndex(
            model_name="report",
            name="ix_report_state_locked",
        ),
        migrations.RemoveIndex(
            model_name="report",
            name="users_repor_state_r_345b80_idx",
        ),
        migrations.RemoveField(
            model_name="block",
            name="state_attempted",
        ),
        migrations.RemoveField(
            model_name="block",
            name="state_ready",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="state_attempted",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="state_ready",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="state_attempted",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="state_ready",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="state_attempted",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="state_ready",
        ),
        migrations.RemoveField(
            model_name="inboxmessage",
            name="state_attempted",
        ),
        migrations.RemoveField(
            model_name="inboxmessage",
            name="state_ready",
        ),
        migrations.RemoveField(
            model_name="passwordreset",
            name="state_attempted",
        ),
        migrations.RemoveField(
            model_name="passwordreset",
            name="state_ready",
        ),
        migrations.RemoveField(
            model_name="report",
            name="state_attempted",
        ),
        migrations.RemoveField(
            model_name="report",
            name="state_ready",
        ),
        migrations.AddField(
            model_name="block",
            name="state_next_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="state_next_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="follow",
            name="state_next_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="identity",
            name="state_next_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inboxmessage",
            name="state_next_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passwordreset",
            name="state_next_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="state_next_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="block",
            name="state_locked_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="domain",
            name="state_locked_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="follow",
            name="state_locked_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="identity",
            name="state_locked_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="inboxmessage",
            name="state_locked_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="passwordreset",
            name="state_locked_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="state_locked_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="block",
            index=models.Index(
                fields=["state", "state_next_attempt", "state_locked_until"],
                name="ix_block_state_next",
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["state", "state_next_attempt", "state_locked_until"],
                name="ix_follow_state_next",
            ),
        ),
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(
                fields=["state", "state_next_attempt", "state_locked_until"],
                name="ix_identity_state_next",
            ),
        ),
        migrations.AddIndex(
            model_name="inboxmessage",
            index=models.Index(
                fields=["state", "state_next_attempt", "state_locked_until"],
                name="ix_inboxmessag_state_next",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordreset",
            index=models.Index(
                fields=["state", "state_next_attempt", "state_locked_until"],
                name="ix_passwordres_state_next",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["state", "state_next_attempt", "state_locked_until"],
                name="ix_report_state_next",
            ),
        ),
        migrations.AddIndex(
            model_name="domain",
            index=models.Index(
                fields=["state", "state_next_attempt", "state_locked_until"],
                name="ix_domain_state_next",
            ),
        ),
    ]
