# Generated by Django 4.2.1 on 2023-07-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_identity_local"),
    ]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="aliases",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
