# Generated by Django 4.2.2 on 2023-07-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_identity_local"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="domain",
            name="ix_domain_state_next",
        ),
    ]
