# Generated by Django 4.2.3 on 2023-08-04 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_identity_aliases"),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM users_follow WHERE state <> 'accepted';"),
    ]
