# Generated by Django 4.2.3 on 2023-11-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_follow_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="indexable",
            field=models.BooleanField(default=False),
        ),
    ]
