# Generated by Django 4.2 on 2023-04-29 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_hashtagfollow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="config",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="config",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configs",
                to="users.domain",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="config",
            unique_together={("key", "user", "identity", "domain")},
        ),
    ]
