# Generated by Django 4.1.3 on 2022-11-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "activities",
            "0004_rename_authored_post_published_alter_fanout_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name="fanout",
            name="type",
            field=models.CharField(
                choices=[
                    ("post", "Post"),
                    ("interaction", "Interaction"),
                    ("undo_interaction", "Undo Interaction"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("post", "Post"),
                    ("boost", "Boost"),
                    ("mentioned", "Mentioned"),
                    ("liked", "Liked"),
                    ("followed", "Followed"),
                    ("boosted", "Boosted"),
                ],
                max_length=100,
            ),
        ),
    ]
