# Generated by Django 4.1.4 on 2022-12-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_emoji_post_emojis"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="type",
            field=models.CharField(
                choices=[
                    ("Article", "Article"),
                    ("Audio", "Audio"),
                    ("Event", "Event"),
                    ("Image", "Image"),
                    ("Note", "Note"),
                    ("Page", "Page"),
                    ("Question", "Question"),
                    ("Video", "Video"),
                ],
                default="Note",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="type_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
