# Generated by Django 4.1.3 on 2022-11-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0005_post_hashtags_alter_fanout_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="hashtags",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
