# Generated by Django 4.1.4 on 2022-12-18 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_report"),
        ("activities", "0005_post_type_timeline_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="fanout",
            name="subject_identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_fan_outs",
                to="users.identity",
            ),
        ),
    ]
