# Generated by Django 4.1.3 on 2022-11-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0006_alter_post_hashtags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="edited",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
