# Generated by Django 4.1.4 on 2023-01-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0007_post_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="postattachment",
            name="original_filename",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
