# Generated by Django 4.1.4 on 2023-01-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0007_post_stats"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="fanout",
            index=models.Index(
                fields=["state", "state_attempted"], name="ix_fanout_state_attempted"
            ),
        ),
        migrations.AddIndex(
            model_name="fanout",
            index=models.Index(
                condition=models.Q(("state_locked_until__isnull", False)),
                fields=["state_locked_until", "state"],
                name="ix_fanout_state_locked",
            ),
        ),
        migrations.AddIndex(
            model_name="hashtag",
            index=models.Index(
                fields=["state", "state_attempted"], name="ix_hashtag_state_attempted"
            ),
        ),
        migrations.AddIndex(
            model_name="hashtag",
            index=models.Index(
                condition=models.Q(("state_locked_until__isnull", False)),
                fields=["state_locked_until", "state"],
                name="ix_hashtag_state_locked",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["visibility", "local", "published"],
                name="ix_post_local_public_published",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["visibility", "local", "created"],
                name="ix_post_local_public_created",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["state", "state_attempted"], name="ix_post_state_attempted"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                condition=models.Q(("state_locked_until__isnull", False)),
                fields=["state_locked_until", "state"],
                name="ix_post_state_locked",
            ),
        ),
        migrations.AddIndex(
            model_name="postattachment",
            index=models.Index(
                fields=["state", "state_attempted"],
                name="ix_postattachm_state_attempted",
            ),
        ),
        migrations.AddIndex(
            model_name="postattachment",
            index=models.Index(
                condition=models.Q(("state_locked_until__isnull", False)),
                fields=["state_locked_until", "state"],
                name="ix_postattachm_state_locked",
            ),
        ),
    ]
