# Generated by Django 4.1.3 on 2022-11-18 01:40

import functools

from django.db import migrations, models

import core.uploads


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0008_postattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postattachment",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    core.uploads.upload_namer, *("attachments",), **{}
                ),
            ),
        ),
    ]
