# Generated by Django 4.1.4 on 2023-02-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0009_alter_timelineevent_index_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emoji",
            name="state_ready",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="fanout",
            name="state_ready",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="hashtag",
            name="state_ready",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="state_ready",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="postattachment",
            name="state_ready",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="postinteraction",
            name="state_ready",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterIndexTogether(
            name="fanout",
            index_together={("state_ready", "state_locked_until", "state")},
        ),
        migrations.AlterIndexTogether(
            name="hashtag",
            index_together={("state_ready", "state_locked_until", "state")},
        ),
        migrations.AlterIndexTogether(
            name="postattachment",
            index_together={("state_ready", "state_locked_until", "state")},
        ),
    ]
