# Generated by Django 4.1.4 on 2023-02-04 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_stator_indexes"),
        ("activities", "0009_alter_timelineevent_index_together"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="emoji",
            index_together={("state_ready", "state_locked_until", "state")},
        ),
        migrations.AlterIndexTogether(
            name="fanout",
            index_together={("state_ready", "state_locked_until", "state")},
        ),
        migrations.AlterIndexTogether(
            name="hashtag",
            index_together={("state_ready", "state_locked_until", "state")},
        ),
        migrations.AlterIndexTogether(
            name="post",
            index_together={("state_ready", "state_locked_until", "state")},
        ),
        migrations.AlterIndexTogether(
            name="postattachment",
            index_together={("state_ready", "state_locked_until", "state")},
        ),
        migrations.AlterIndexTogether(
            name="postinteraction",
            index_together={
                ("type", "identity", "post"),
                ("state_ready", "state_locked_until", "state"),
            },
        ),
    ]
