# Generated by Django 4.1.5 on 2023-02-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0010_stator_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="postinteraction",
            name="answer",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="postinteraction",
            name="type",
            field=models.CharField(
                choices=[("like", "Like"), ("boost", "Boost"), ("vote", "Vote")],
                max_length=100,
            ),
        ),
    ]
