# Generated by Django 4.1.4 on 2023-03-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0011_postinteraction_value_alter_postinteraction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="in_reply_to",
            field=models.CharField(
                blank=True, db_index=True, max_length=500, null=True
            ),
        ),
    ]
