# Generated by Django 4.1.4 on 2023-03-12 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_bookmark"),
        ("activities", "0012_in_reply_to_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="postattachment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="users.identity",
            ),
        ),
    ]
