# Generated by Django 4.2 on 2023-04-29 18:49

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0013_postattachment_author"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "content", config="english"
                ),
                name="content_vector_gin",
            ),
        ),
    ]
