# Generated by Django 4.1.7 on 2023-04-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0014_post_content_vector_gin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postinteraction",
            name="type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("boost", "Boost"),
                    ("vote", "Vote"),
                    ("pin", "Pin"),
                ],
                max_length=100,
            ),
        ),
    ]
