# Generated by Django 4.2.1 on 2023-07-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0016_index_together_migration"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="emoji",
            name="activities__state_r_aa72ec_idx",
        ),
        migrations.RemoveIndex(
            model_name="emoji",
            name="ix_emoji_state_attempted",
        ),
        migrations.RemoveIndex(
            model_name="emoji",
            name="ix_emoji_state_locked",
        ),
        migrations.RemoveIndex(
            model_name="fanout",
            name="ix_fanout_state_attempted",
        ),
        migrations.RemoveIndex(
            model_name="fanout",
            name="ix_fanout_state_locked",
        ),
        migrations.RemoveIndex(
            model_name="fanout",
            name="activities__state_r_aae3b4_idx",
        ),
        migrations.RemoveIndex(
            model_name="hashtag",
            name="ix_hashtag_state_attempted",
        ),
        migrations.RemoveIndex(
            model_name="hashtag",
            name="ix_hashtag_state_locked",
        ),
        migrations.RemoveIndex(
            model_name="hashtag",
            name="activities__state_r_5703be_idx",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="ix_post_state_attempted",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="ix_post_state_locked",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="activities__state_r_b8f1ff_idx",
        ),
        migrations.RemoveIndex(
            model_name="postattachment",
            name="ix_postattachm_state_attempted",
        ),
        migrations.RemoveIndex(
            model_name="postattachment",
            name="ix_postattachm_state_locked",
        ),
        migrations.RemoveIndex(
            model_name="postattachment",
            name="activities__state_r_4e981c_idx",
        ),
        migrations.RemoveIndex(
            model_name="postinteraction",
            name="activities__state_r_981d8c_idx",
        ),
        migrations.RemoveIndex(
            model_name="postinteraction",
            name="ix_postinterac_state_attempted",
        ),
        migrations.RemoveIndex(
            model_name="postinteraction",
            name="ix_postinterac_state_locked",
        ),
        migrations.RemoveField(
            model_name="emoji",
            name="state_attempted",
        ),
        migrations.RemoveField(
            model_name="emoji",
            name="state_ready",
        ),
        migrations.RemoveField(
            model_name="fanout",
            name="state_attempted",
        ),
        migrations.RemoveField(
            model_name="fanout",
            name="state_ready",
        ),
        migrations.RemoveField(
            model_name="hashtag",
            name="state_attempted",
        ),
        migrations.RemoveField(
            model_name="hashtag",
            name="state_ready",
        ),
        migrations.RemoveField(
            model_name="post",
            name="state_attempted",
        ),
        migrations.RemoveField(
            model_name="post",
            name="state_ready",
        ),
        migrations.RemoveField(
            model_name="postattachment",
            name="state_attempted",
        ),
        migrations.RemoveField(
            model_name="postattachment",
            name="state_ready",
        ),
        migrations.RemoveField(
            model_name="postinteraction",
            name="state_attempted",
        ),
        migrations.RemoveField(
            model_name="postinteraction",
            name="state_ready",
        ),
        migrations.AddField(
            model_name="emoji",
            name="state_next_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fanout",
            name="state_next_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hashtag",
            name="state_next_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="state_next_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="postattachment",
            name="state_next_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="postinteraction",
            name="state_next_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emoji",
            name="state_locked_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="fanout",
            name="state_locked_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="hashtag",
            name="state_locked_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="state_locked_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="postattachment",
            name="state_locked_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="postinteraction",
            name="state_locked_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="emoji",
            index=models.Index(
                fields=["state", "state_next_attempt", "state_locked_until"],
                name="ix_emoji_state_next",
            ),
        ),
        migrations.AddIndex(
            model_name="fanout",
            index=models.Index(
                fields=["state", "state_next_attempt", "state_locked_until"],
                name="ix_fanout_state_next",
            ),
        ),
        migrations.AddIndex(
            model_name="hashtag",
            index=models.Index(
                fields=["state", "state_next_attempt", "state_locked_until"],
                name="ix_hashtag_state_next",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["state", "state_next_attempt", "state_locked_until"],
                name="ix_post_state_next",
            ),
        ),
        migrations.AddIndex(
            model_name="postattachment",
            index=models.Index(
                fields=["state", "state_next_attempt", "state_locked_until"],
                name="ix_postattachm_state_next",
            ),
        ),
        migrations.AddIndex(
            model_name="postinteraction",
            index=models.Index(
                fields=["state", "state_next_attempt", "state_locked_until"],
                name="ix_postinterac_state_next",
            ),
        ),
    ]
