# Generated by Django 4.2.2 on 2023-07-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0017_stator_next_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineevent",
            name="dismissed",
            field=models.BooleanField(default=False),
        ),
    ]
