# Generated by Django 4.2.3 on 2023-08-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0018_timelineevent_dismissed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelineevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("post", "Post"),
                    ("boost", "Boost"),
                    ("mentioned", "Mentioned"),
                    ("liked", "Liked"),
                    ("followed", "Followed"),
                    ("follow_requested", "Follow Requested"),
                    ("boosted", "Boosted"),
                    ("announcement", "Announcement"),
                    ("identity_created", "Identity Created"),
                ],
                max_length=100,
            ),
        ),
    ]
