# Generated by Django 4.2.3 on 2023-10-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0018_timelineevent_dismissed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postattachment",
            name="focal_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="postattachment",
            name="focal_y",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
