# Generated by Django 4.1.3 on 2022-11-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=500)),
                ("priority", models.IntegerField(default=0)),
                ("subject", models.TextField()),
                ("payload", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("completed", models.DateTimeField(blank=True, null=True)),
                ("failed", models.DateTimeField(blank=True, null=True)),
                ("locked", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
