# Generated by Django 4.1.3 on 2022-11-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StatorTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_label", models.CharField(max_length=200)),
                ("instance_pk", models.CharField(max_length=200)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("priority", models.IntegerField(default=0)),
            ],
        ),
    ]
