# Generated by Django 4.1.3 on 2022-11-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StatorError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_label", models.CharField(max_length=200)),
                ("instance_pk", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("error", models.TextField()),
                ("error_details", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
