# Generated by Django 4.1.4 on 2022-12-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stats",
            fields=[
                (
                    "model_label",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("statistics", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Stats",
            },
        ),
        migrations.DeleteModel(
            name="StatorError",
        ),
    ]
